config/routes.rb
GroupCrud::Application.routes.draw do

 root :to => 'artists#index', as: "root"
 resources :artists

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :number_of_albums
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	def index
		@artists = Artist.all
	end

	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.create(params[:artist])
		redirect_to root_path
	end

	def edit
		@artist = Artist.find(params[:id])
	end

	def update
		artist = Artist.find(params[:id])
		artist.update_attributes(params[:artist])
		artist.save

		redirect_to root_path
	end

	def delete
		artist = Artist.find(params[:id])
		artist.destroy
		redirect_to root_path
	end
	
	def show
		@artist = Artist.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for artist do |f| %>
<%= f.label "Artist Name:" %>
<%= f.text_field :name, size: "15"%>
<%= f.label "Number of Albums:" %>
<%= f.text_field :number_of_albums, size: "15" %>
<%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<%= render partial: "form", locals: {artist: @artist} %>

app/views/artists/index.html.erb
<div class = "artist-button">
<%= button_to "New Artist", new_artist_path, :method => :get %>
</div>

<!-- <div class="row" id="show-button">Click to see artists!</div> -->
<div id="artists-div">
	<ul id = "artist-list">
	<% @artists.each do |artist| %>
		<li>
			<h3 class="artist-name">
			<%= artist.name %>
			</h3>
			<p>Number of albums: <%= artist.number_of_albums %></p>

		</li>
			<% end %>

	</ul>

</div>
<br>

app/views/artists/new.html.erb
<%= render partial: "form", locals: {artist: @artist} %>

app/views/artists/show.html.erb
<table>
  <thead>
    <td>Name</td>
    <td>Albums</td>
  </thead>
  <tbody>
    <tr>
      <td><%= @artist.name %></td>
      <td><%= @artist.number_of_albums %></td>
    </tr>
  </tbody>
</table>

app/views/artists/update.html.erb
<%= render partial: "form", locals: {artist: @artist[:id]} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Artists</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
		<body>
			<div class="bgwrapper full-width-container">
				<div class = "container">
					<h2 class="page-header"> Artists </h2>
						<hr>
						<br>
					<div class = "content">
						<br>
					<%= yield %>
				<!-- 		<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br> -->

						<!-- <hr> -->
					</div>
				</div>
			</div>
</body>
</html>